### ISSUE TITLE
PEER REVIEW: 28/04/2023

### ISSUE THREAD

**Issue by Ochiengsteven** [MenendezON/HaitTechSubmit#2]
Good work so far on you website so far Nelson 👏 
however I would recommed the following changes:

- work on the partners images layout on the mobile view
- work on the layout of the past events to match with  the original design

**Comment by MenendezON** [comment]
> Good work so far on you website so far Nelson 👏 however I would recommed the following changes:
> 
> * work on the partners images layout on the mobile view
> * work on the layout of the past events to match with  the original design

Thank you Sir, I'll take into account your comments
